---
name: Generate changelog
description: Generate changelog from an issue comments
inputs:
  token:
    description: Token (secrets.GITHUB_TOKEN)
    required: true
outputs:
  changelog:
    description: The format changelog text
runs:
  using: node20
  main: action/index.js